# --- Настройки для Black
[tool.black]
# Устанавливаем длину строки в 120 символов
line-length = 120
# Указываем версии Python, с которыми будет совместим код
target-version = ['py312']
# Настройка для сохранения кавычек как есть от пользователя
# skip-string-normalization = false в black означает,
# что black будет автоматически преобразовывать кавычки в один стиль (по умолчанию — в двойные ").
skip-string-normalization = true
# Форматировать только Python файлы
include = '\.py$'

# --- Настройки для Isort
[tool.isort]
# Устанавливаем ту же длину строки, что и в Black
line_length = 120
# Указываем что используется совместимо с плагином Black (если установлен)
profile = "black"
# Используем стиль Black для многстрочных импортов
multi_line_output = 3
# Добавляем запятую в конце многстрочного импорта
include_trailing_comma = true
# Разделяем импорты стандартных библиотек, сторонних библиотек и локальных модулей
lines_between_types = 1
# Включаем круглые скобки для многострочных импортов
use_parentheses = true
# Разрешаем добавление пустых строк между типами импортов
ensure_newline_before_comments = true
