# Словарь со ссылками на видео, если в папке(tasks_video) нет физических файлов видео,
# программа проверяет если в папке tasks_video приложения есть физически видео-файл для занятия,
# файл будет запущен во встроенном плеере ОС Windows.
# Если видео файл для занятия в папке tasks_video не найден,
# приложение переключится на воспроизведение видео с YouTube открыв браузер ОС Windows назначенного по умолчанию.
#
# !!! ФАЖНО файлы с видео для занятий можно скачать с google-drive по адресу:
# https://drive.google.com/file/d/17YC7R-i_D0Ntimtfeuo0Jj3A9VKnNvNF/view?usp=drive_link
# Распакуйте видео в папку tasks_video по пути: C:\Program Files (x86)\Basics Python Beginners\tasks_video
# все будет работать автономно во встроенном плеере ОС Windows.

tasks_video_links = {
    'vid_1.2 Первое знакомство с Python  Установка на компьютер': 'https://www.youtube.com/watch?v=btuxcr7Sxw4',
    'vid_1.3 Варианты исполнения команд. Переходим в PyCharm': 'https://www.youtube.com/watch?v=fb5f0jX9tng',
    'vid_2.1 Переменные, оператор присваивания, функции type и id': 'https://www.youtube.com/watch?v=qJwkaKgNxfE',
    'vid_2.2 Числовые типы, арифметические операции': 'https://www.youtube.com/watch?v=HZrbYY10cJI',
    'vid_2.3 Математические функции и работа с модулем math': 'https://www.youtube.com/watch?v=iXbZb176OFo',
    'vid_2.4 Функции print() и input(). Преобразование строк в числа int() и float()': 'https://www.youtube.com/watch?v=8hzpSR_Qaj8',
    'vid_2.5 Логический тип bool. Операторы сравнения и операторы and, or, not': 'https://www.youtube.com/watch?v=Bn-uGQA9-kQ',
    'vid_3.1 Введение в строки. Базовые операции над строками': 'https://www.youtube.com/watch?v=v1yHG6HGfGQ',
    'vid_3.2 Знакомство с индексами и срезами строк': 'https://www.youtube.com/watch?v=UNdy_1PsXnU',
    'vid_3.3 Основные методы строк': 'https://www.youtube.com/watch?v=TEF-0UXRybg',
    'vid_3.4 Спецсимволы, экранирование символов, raw-строки': 'https://www.youtube.com/watch?v=VZsWVN6QaKc',
    'vid_3.5 Форматирование строк: метод format и F-строки': 'https://www.youtube.com/watch?v=DOxzzkjTcgI',
    'vid_3.6 Списки - операторы и функции работы с ними': 'https://www.youtube.com/watch?v=HgFGVQG20Oc',
    'vid_3.7 Срезы списков и сравнение списков': 'https://www.youtube.com/watch?v=Vx3s01Yb1P8',
    'vid_3.8 Основные методы списков': 'https://www.youtube.com/watch?v=1r9X3drypHk',
    'vid_3.9 Вложенные списки, многомерные списки': 'https://www.youtube.com/watch?v=FBCufeNGQio',
    'vid_4.1 Условный оператор if. Конструкция if-else': 'https://www.youtube.com/watch?v=jBP8RY2-m74',
    'vid_4.2 Вложенные условия и множественный выбор. Конструкция if-elif-else': 'https://www.youtube.com/watch?v=7L-wetlrCi0',
    'vid_4.3 Тернарный условный оператор. Вложенное тернарное условие': 'https://www.youtube.com/watch?v=SotePVO6_Fk',
    'vid_5.1 Оператор цикла while': 'https://www.youtube.com/watch?v=5BRzUFyOWYI',
    'vid_5.2 Операторы циклов break, continue и else': 'https://www.youtube.com/watch?v=y35dyh7cbXY',
    'vid_5.3 Оператор цикла for. Функция range()': 'https://www.youtube.com/watch?v=ogeX44jsIqg',
    'vid_5.4 Примеры работы оператора цикла for. Функция enumerate()': 'https://www.youtube.com/watch?v=ycBzUTOmyVQ',
    'vid_5.5 Итератор и итерируемые объекты. Функции iter() и next()': 'https://www.youtube.com/watch?v=Kro9UOtkZEk',
    'vid_5.6 Вложенные циклы. Примеры задач с вложенными циклами': 'https://www.youtube.com/watch?v=S5SiNuV5f7g',
    'vid_5.7 Треугольник Паскаля как пример работы вложенных циклов': 'https://www.youtube.com/watch?v=ptq-3bOwgpw',
    'vid_5.8 Генераторы списков (List comprehensions) ': 'https://www.youtube.com/watch?v=0QJV31Xy44o',
    'vid_5.9 Вложенные генераторы списков': 'https://www.youtube.com/watch?v=wOpKlNF7JIQ',
    'vid_6.1 Введение в словари (dict). Базовые операции над словарями': 'https://www.youtube.com/watch?v=JV2olufru8Q',
    'vid_6.2 Методы словаря, перебор элементов словаря в цикле': 'https://www.youtube.com/watch?v=pZqll5OVbLo',
    'vid_6.3 Кортежи (tuple) и их методы': 'https://www.youtube.com/watch?v=JVEBE7pviE0',
    'vid_6.4 Множества (set) и их методы': 'https://www.youtube.com/watch?v=Z3lw-yMZKuQ',
    'vid_6.5 Операции над множествами, сравнение множеств': 'https://www.youtube.com/watch?v=0lPDdSX76z4',
    'vid_6.6 Генераторы множеств и генераторы словарей': 'https://www.youtube.com/watch?v=xbTeGaWxrdY',
    'vid_7.1 Функции: первое знакомство, определение def и их вызов': 'https://www.youtube.com/watch?v=NUrEyTW4JuU',
    'vid_7.2 Оператор return в функциях. Функциональное программирование': 'https://www.youtube.com/watch?v=D2uB3vqMTzI',
    'vid_7.3 Алгоритм Евклида для нахождения НОД': 'https://www.youtube.com/watch?v=IEORD_eVfCo',
    'vid_7.4 Именованные аргументы. Фактические и формальные параметры': 'https://www.youtube.com/watch?v=8Z-_PpJbkdI',
    'vid_7.5 Функции с произвольным числом параметров *args и **kwargs': 'https://www.youtube.com/watch?v=6Kk7luuKPGQ',
    'vid_7.6 Операторы * и ** для упаковки и распаковки коллекций': 'https://www.youtube.com/watch?v=D6-d5yWOBd0',
    'vid_7.7 Рекурсивные функции': 'https://www.youtube.com/watch?v=dtzoBXL11oo',
    'vid_7.7-1 Рекурсивные функции ч2': 'https://www.youtube.com/watch?v=yQn6wBKAjHA',
    'vid_7.7-2 Хвостовая рекурсия': 'https://www.youtube.com/watch?v=jvVhV35uIRs',
    'vid_7.8 Анонимные (lambda) функции': 'https://www.youtube.com/watch?v=UAYeh7pSqXw',
    'vid_7.9 Области видимости переменных. Ключевые слова global и nonlocal': 'https://www.youtube.com/watch?v=TacyWpUF1Kk',
    'vid_7.10 Замыкания в Python': 'https://www.youtube.com/watch?v=sJF7OMNgLUs',
    'vid_7.11 Введение в декораторы функций': 'https://www.youtube.com/watch?v=v0qZPplzwUQ',
    'vid_7.12 Декораторы с параметрами. Сохранение свойств декорируемых функций': 'https://www.youtube.com/watch?v=bl_CnIVpWmQ',
    'vid_8.1 Импорт стандартных модулей. Команды import и from': 'https://www.youtube.com/watch?v=3b4OfynySaQ',
    'vid_8.2 Импорт собственных модулей': 'https://www.youtube.com/watch?v=hWsBYrASuqU',
    'vid_8.3 Установка сторонних модулей (pip install). Пакетная установка': 'https://www.youtube.com/watch?v=xSsKtIiUaOY',
    'vid_8.4 Пакеты (package) в Python. Вложенные пакеты': 'https://www.youtube.com/watch?v=6K1f0DvW1uM',
    'vid_8.5 Функция open. Чтение данных из файла': 'https://www.youtube.com/watch?v=ZlwGi3fOcvY',
    'vid_8.6 Исключение FileNotFoundError и менеджер контекста (with) для файлов': 'https://www.youtube.com/watch?v=tM5qE8YLLuo',
    'vid_8.7 Запись данных в файл в текстовом и бинарном режимах': 'https://www.youtube.com/watch?v=vJ0PZQj9AUs',
    'vid_9.1 Выражения генераторы': 'https://www.youtube.com/watch?v=cJxrUY7AvpA',
    'vid_9.2 Функция-генератор. Оператор yield': 'https://www.youtube.com/watch?v=_k9CoVcNoMU',
    'vid_9.3 Функция map. Примеры ее использования': 'https://www.youtube.com/watch?v=L0hHz323B7Y',
    'vid_9.4 Функция filter для отбора значений итерируемых объектов': 'https://www.youtube.com/watch?v=nV-skNFfzbo',
    'vid_9.5 Функция zip. Примеры использования': 'https://www.youtube.com/watch?v=73moTN-nyhA',
    'vid_9.6 Особенности сортировки через sort() и sorted()': 'https://www.youtube.com/watch?v=yR_rqQX7t3M',
    'vid_9.7 Аргумент key для сортировки коллекций по ключу': 'https://www.youtube.com/watch?v=M_1cYWm3VyE',
    'vid_9.8 Функции isinstance и type для проверки типов данных': 'https://www.youtube.com/watch?v=kxGDjKteb7w',
    'vid_9.9 Функции all и any. Примеры их использования': 'https://www.youtube.com/watch?v=CrIt8leToH0',
    'vid_10.1 Расширенное представление чисел. Системы счисления': 'https://www.youtube.com/watch?v=Dw5z1SPq77A',
    'vid_10.2 Битовые операции И, ИЛИ, НЕ, XOR. Сдвиговые операторы': 'https://www.youtube.com/watch?v=myW_9B9T_II',
    'vid_10.3 Модуль random стандартной библиотеки': 'https://www.youtube.com/watch?v=F5SYEE6eT28',
    'vid_10.4 Конструкция match/case. Первое знакомство ': 'https://www.youtube.com/watch?v=yDlWEwG1eb0',
    'vid_10.5 Конструкция match/case с кортежами и списками ': 'https://www.youtube.com/watch?v=wfTqJVo7JM4',
    'vid_10.6 Конструкция match/case со словарями и множествами': 'https://www.youtube.com/watch?v=iZISBwtNGvM',
    'vid_10.7 Конструкция match/case. Примеры и особенности использования ': 'https://www.youtube.com/watch?v=dmwhEA1ISyk',
    'vid_10.9 Аннотация базовыми типами': 'https://www.youtube.com/watch?v=29WDYmT4e1E',
    'vid_10.10 Аннотации типов коллекций': 'https://www.youtube.com/watch?v=HYB_z6n7cKQ',
    'vid_10.11 Аннотации типов на уровне классов': 'https://www.youtube.com/watch?v=Wq7XfZTrATU',
    'vid_10.12 Моржовая операция присваивания (walrus operator)': 'https://www.youtube.com/watch?v=PYLQkzar6bo&t',
}
